# Form implementation generated from reading ui file 'NewTask.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_NewTask(object):
    def setupUi(self, NewTask):
        NewTask.setObjectName("NewTask")
        NewTask.resize(430, 270)
        NewTask.setMinimumSize(QtCore.QSize(430, 270))
        NewTask.setMaximumSize(QtCore.QSize(430, 270))
        
        #########    Center Windows      #####
        qr = Ui_NewTask.frameGeometry()
        cp = QtGui.QGuiApplication.primaryScreen().availableGeometry().center()
        qr.moveCenter(cp)
        Ui_NewTask.move(qr.topLeft())
        #######################################
        
        self.editTask = QtWidgets.QLineEdit(NewTask)
        self.editTask.setGeometry(QtCore.QRect(139, 40, 240, 27))
        self.editTask.setObjectName("editTask")
        self.label = QtWidgets.QLabel(NewTask)
        self.label.setGeometry(QtCore.QRect(96, 44, 101, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NewTask)
        self.label_2.setGeometry(QtCore.QRect(50, 94, 161, 19))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(NewTask)
        self.groupBox.setGeometry(QtCore.QRect(1, 1, 428, 268))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.buttonAccept = QtWidgets.QPushButton(self.groupBox)
        self.buttonAccept.setGeometry(QtCore.QRect(110, 207, 88, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/accept.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonAccept.setIcon(icon)
        self.buttonAccept.setObjectName("buttonAccept")
        self.buttonCancel = QtWidgets.QPushButton(self.groupBox)
        self.buttonCancel.setGeometry(QtCore.QRect(240, 207, 88, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonCancel.setIcon(icon1)
        self.buttonCancel.setObjectName("buttonCancel")
        self.editDescription = QtWidgets.QTextEdit(self.groupBox)
        self.editDescription.setGeometry(QtCore.QRect(139, 89, 240, 90))
        self.editDescription.setObjectName("editDescription")
        self.groupBox.raise_()
        self.editTask.raise_()
        self.label.raise_()
        self.label_2.raise_()

        self.retranslateUi(NewTask)
        QtCore.QMetaObject.connectSlotsByName(NewTask)

    def retranslateUi(self, NewTask):
        _translate = QtCore.QCoreApplication.translate
        NewTask.setWindowTitle(_translate("NewTask", "New Task"))
        self.label.setText(_translate("NewTask", "Task:"))
        self.label_2.setText(_translate("NewTask", "Description:"))
        self.buttonAccept.setText(_translate("NewTask", "Accept"))
        self.buttonCancel.setText(_translate("NewTask", "Cancel"))
